image: node:12.8.0

# And to cache them as well.
cache:
  paths:
    - node_modules/
    - .yarn

before_script:
  - apt-get update -qq && apt-get install

stages:
  - build
  - test
  - staging

cache:
  paths:
    - node_modules/

Build_The_App:

  stage: build
  only:
    - merge_requests
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

Test:
  only:
    - merge_requests
  stage: test
  script: npm test

Deploy to Staging:
  stage: staging
  tags: 
    - demo
  before_script:
    - mkdir -p ~/.ssh
    - 'echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - bash ./.gitlab/deploy-staging.sh
  environment:
    name: staging
    url: http://ec2-54-193-57-240.us-west-1.compute.amazonaws.com:3000
